services:
  # Airflow metadata database
  postgres:
    image: postgres:13
    container_name: airflow_db
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_db_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"  # Expose different port to avoid conflict with your other Postgres

  # Redis - required by Airflow for queues
  redis:
    image: redis:7.2-bookworm
    container_name: airflow_redis
    restart: always
    ports:
      - "6379:6379"

  mongo:
    image: mongo:6.0
    container_name: airflow_mongo
    restart: always
    ports:
      - "27017:27017"
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]


  # Main Airflow container (webserver + scheduler)
  airflow:
    build: .
    container_name: airflow
    restart: always
    depends_on:
      - postgres
      - redis
      - mongo
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow_db:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: "a_random_secure_key"  # can be anything
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "False"
      AIRFLOW__WEBSERVER__SECRET_KEY: "super_secret_key"
    ports:
      - "8080:8080"
    volumes:
      - ../orchestrator/dags:/opt/airflow/dags
      - ../services:/opt/airflow/services
      - ../dbt/nomba_analytics:/opt/airflow/dbt/nomba_analytics

      
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create --username admin --password admin --firstname Adewale --lastname Akangbe --role Admin --email admin@example.com &&
      airflow webserver --port 8080 &
      sleep 10 &&
      airflow scheduler
      "

volumes:
  airflow_db_data:
